name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Zip custom_components
        run: |
          cd custom_components/kinetico_powerline
          zip kinetico_powerline.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/kinetico_powerline/kinetico_powerline.zip

      - name: Delete older releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for tag in $(gh release list -L 100 --json tagName -q '.[].tagName'); do
            if [ "$tag" != "${{ github.event.release.tag_name }}" ]; then
              gh release delete "$tag" --yes
            fi
          done
